### ISSUE TITLE
add flagship filter, and allow any combination of labor/faith/flagship

### ISSUE THREAD

**Issue by mikelmaron** [wearemarchon/strikewithus#14]
@meganrm I've updated the data to include three boolean fields "faith", "labor", "flagship". That should make it easier to implement expressions for filtering on combinations of these.

**Comment by meganrm** [comment]
thanks @mikelmaron is there still only the one faith event? All three things are false for all the other events?

**Comment by mikelmaron** [comment]
yea there's still only one test faith event.

if you need for testing, copy and modify a local copy, and point code there @meganrm
